services:
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    restart: unless-stopped
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    restart: unless-stopped
